#
# obsidian personal configuration
#

compdef _obsidian_cli_complete obsidian-cli

_obsidian_cli_complete() {
    local -a commands
    local cmdfile=/usr/local/src/obsidian/cmd/help
    if [[ -f "$cmdfile" ]]; then
        commands=("${(@f)$(< "$cmdfile")}")
    else
        commands=("help:Could not load commands file")
    fi
    _describe 'command' commands
}

#fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit

# Trash
TRASH=$HOME/.local/share/Trash

if [[ $DEBUG = "true" ]]; then
    # prefixo de debug para o bash
    export PS4='+ ${BASH_SOURCE}:${LINENO}:${FUNCNAME[0]}: '

    # saída do trace para stderr
    export BASH_XTRACEFD=2
fi