#! /bin/bash

# _rm_item() {
#     local to_remove="$1"
#     shift
#     local result=()
#     for val in "$@"; do
#         [[ "$val" != "$to_remove" ]] && result+=("$val")
#     done
#     echo "${result[@]}"
# }

_help() {
    echo "$1"
    echo ""
    echo "Uso: $0 <cmd> [options]"
    echo ""
    echo "Comandos disponíveis:"
    echo ""
    echo "  build <base> <name>            Constrói a imagem Docker"
    echo ""
    echo "  create-vault <version>         Cria um novo vault "
    echo ""
    echo "  run <name> [options]           Executa o contêiner"
    echo "    -r            Executar como root"
    echo "    -t            Usar shell em vez do app"
    echo "    -v <vault>    Montar cofre"
    echo "    -s <storage>  Montar armazenamento"
    echo "    -c <cmd>      Montar cmd"
    echo "    -e <ext>      Adicionar extensão ao nome"
    echo ""
    exit 1
}

source ./env

VERSION=${VERSION:"001.002.000"}
OP=$1

shift 1

case "$OP" in
    run)
        IMG_NAME=${1:-"$IMG_NAME"}
        echo "IMG_NAME: $IMG_NAME"

        [[ "$IMG_NAME" == "" ]] && _help 'Err: IMG_NAME not defined' && exit 1

        OP_DOCKER=(
            --env-file ./env
            --env VERSION=$VERSION
            -p 5000:5000
        )

        OP_EXE="-d"
        EXE="/usr/local/bin/obsidian-main"
        EXTENSION="run."

        shift 1

        while getopts 'rtv:s:c:e:' OP; do
            case "$OP" in
                r)
                # entrar como root
                    OP_DOCKER+=(-u 0)
                    ;;
                t)
                # executar terminal
                    EXE="/bin/bash"
                    OP_EXE="-ti"
                    ;;
                v)
                # caminho do vault
                    VAULT=$OPTARG
                    ;;
                s)
                # caminho do storage
                    STORAGE=$OPTARG
                    ;;
                c)
                # caminho do cmd
                    CMD=${OPTARG:-"$CMD"}
                    [ ! -d "$CMD" ] && \
                        _help "Err: CMD:\"$CMD\" not found"
                    OP_DOCKER+=(-v $CMD:/usr/local/src/obsidian/cmd)
                    ;;
                e)
                # extensão do container
                    EXTENSION="$EXTENSION$OPTARG."
                    ;;
                *)
                    _help
                    ;;
            esac
        done

        shift $(($OPTIND -1))

        IMAGE="app.$IMG_NAME"
        CONTAINER="$EXTENSION$IMG_NAME"

        if ! [[ $VAULT == "" ]]; then
            [ ! -d "$VAULT" ] && \
                _help "Err: VAULT:\"$VAULT\" not found"
            OP_DOCKER+=(-v $VAULT:/mnt/vault)
        fi

        if ! [[ $STORAGE == "" ]]; then
            [ ! -d "$STORAGE" ] && \
                _help "Err: STORAGE:\"$STORAGE\" not found"
            OP_DOCKER+=(-v $STORAGE:/mnt/storage)
        fi

        echo "VAULT: $VAULT"
        echo "STORAGE: $STORAGE"

        docker run "${OP_DOCKER[@]}" --name "$CONTAINER" --rm "$OP_EXE" "$IMAGE" "$EXE"

        ;;
    build)
        IMG_BASE=${1:-"$IMG_BASE"}
        IMG_NAME=${2:-"$IMG_NAME"}
        
        echo "IMG_BASE: $IMG_BASE"
        echo "IMG_NAME: $IMG_NAME"

        [[ "$IMG_BASE" == "" ]] && _help 'Err: IMG_BASE not defined'
        [[ "$IMG_NAME" == "" ]] && _help 'Err: IMG_NAME not defined'

        docker build \
            --build-arg USER=$(whoami) \
            --build-arg UID=$(id -u) \
            --build-arg GID=$(id -g) \
            --build-arg IMG=app.$IMG_BASE \
            -t app.$IMG_NAME .
        ;;
    *)
        _help
        ::
esac