#
# obsidian personal configuration
#

source $HOME/.obsidian-cli/env

compdef _obsidian_cli_complete obsidian-cli

_obsidian_cli_complete() {
    local -a commands
    local cmdfile=$VAULT/sys/cmd/help
    if [[ -f "$cmdfile" ]]; then
        commands=("${(@f)$(< "$cmdfile")}")
    else
        commands=("help:Could not load commands file")
    fi
    _describe 'command' commands
}

#fpath=(~/.zsh/completion $fpath)
autoload -Uz compinit && compinit

# Trash
TRASH=$HOME/.local/share/Trash